require "ruboty"
require "ruboty/niftycloud/actions/base"
require "ruboty/niftycloud/actions/account_list"
require "ruboty/niftycloud/actions/account_use"
require "ruboty/niftycloud/actions/computing_region_list"
require "ruboty/niftycloud/actions/computing_region_use"
require "ruboty/niftycloud/actions/computing_instance_list"
require "ruboty/niftycloud/actions/computing_instance_show"
require "ruboty/niftycloud/actions/computing_security_group_list"
require "ruboty/niftycloud/actions/computing_security_group_show"
require "ruboty/niftycloud/actions/computing_volume_list"
require "ruboty/niftycloud/actions/computing_volume_show"
require "ruboty/niftycloud/actions/computing_load_balancer_list"
require "ruboty/niftycloud/actions/computing_load_balancer_show"
require "ruboty/niftycloud/version"
require "ruboty/handlers/niftycloud"

require "ace-client"
