require "ruboty"
require "ruboty/niftycloud/actions/base"
require "ruboty/niftycloud/actions/account_list"
require "ruboty/niftycloud/actions/account_use"
require "ruboty/niftycloud/actions/computing_region_list"
require "ruboty/niftycloud/actions/computing_region_use"
require "ruboty/niftycloud/actions/computing_instance_list"
require "ruboty/niftycloud/actions/computing_instance_show"
require "ruboty/niftycloud/version"
require "ruboty/handlers/niftycloud"

require "ace-client"
